snyk/docs

_docs_faqs/4_using-Snyk.md, _docs_quick-start/1_set-up.md, _docs_using-snyk/2_authentication.md, _docs_using-snyk/3_wizard.md, _docs_using-snyk/4_test.md
Text edits
[ x] Review @johannakoll
=> chore: text edits

_docs_github/1_how-to-integrate.md, _docs_github/2_integration_features.md, _docs_orgs/2_creating-org.md, _docs_orgs/5_collaborating.md, github-integration.md
Fix cloudinary URLs to apply automated optimization. 
My editor trimmed some spaces which I figured I might as well check in too. 
- Confirm code changes are only cloudinary
- Look at the repo locally and confirm visuals are fine
=> fix: optimize cloudinary images

_config.yml, _docs_badges/0_intro.md, _docs_badges/1_npm_badges.md, _docs_badges/2_github_badges.md, _docs_badges/3_private_repo.md, _docs_using-snyk/8_badge.md, _layouts/docs.html, _site/feed.json, badges/index.html, feed.json
This is _mostly_ done, but needs some testing and I think one more change to `nav-tree.scss` in registry partials? Am I reading that correctly?
Creates a section for Badges, and makes the old badges section point to it. 
Also slightly reorders menu items.
I'm not sure. One aspect is text and code review, but the styling is broken locally.
=> docs: created badges section

_docs_github/1_how-to-integrate.md, _site/feed.json
=> docs: updated docs to match latest implementation

_docs_slack-integration/1_installation.md
=> feat: add documentation for Slack integration

_includes/head.html
Updates the page metadata to refer to Ruby support as well as Node.js
Any page!
- View source and check that all metadata in the `<head>` looks good.
- Maybe check the og and twitter tags with:
https://developers.facebook.com/tools/debug/
https://cards-dev.twitter.com/validator
=> feat: update page metadata in the head

_docs_landing/0_intro.md, _docs_using-snyk/9_CLI-command-overview.md
This PR contains the new content for the docs landing page (minimum effort...), and a commit to move the CLI commands overview from the landing page to the CLI section.
=> Docs landing page updates

_docs_ci/1_build-integration.md, _docs_ci/2_ruby-build-integration.md, _docs_ci/3_API-token-configuration.md, _docs_using-snyk/0_intro.md, _docs_using-snyk/1_installation.md, _docs_using-snyk/2_authentication.md, _docs_using-snyk/3_wizard.md, _docs_using-snyk/4_test.md, _docs_using-snyk/5_protect.md, _docs_using-snyk/7_dev-integration.md, _docs_using-snyk/9_CLI-command-overview.md
=> docs: update CLI docs for Ruby CLI release

_docs_github/1_how-to-integrate.md, _docs_github/4_fix_vulnerabilities_web_flow.md, _docs_github/6_authorizing-github.md
This PR updates the GitHub integration with
- info about granting public and/or private repo access
- Ruby fixes (Gemfile changes)
=> docs: updates to GitHub integration

_docs_security/1_how-snyk-finds-vulns.md
@johannakoll @grnd  can you please review?
=> Update how we discover vulnerabilities

_docs_quick-start/5_ignore.md, github-integration.md
https://github.com/snyk/pages/pull/28
=> feat: SC-2993 rename "VulnDB" to "Vulnerability DB"

_docs_ruby/1_support.md, _docs_ruby/3_fixing.md
Call out: If your Gemfile needs access to private Gem sources please [get in touch]
=> fix: add info about private gem sources

_docs_using-snyk/03_wizard.md
=> fix: removing a p tag

_docs_nodejs/1_support.md, _docs_quick-start/6_applying-your-choices.md, _docs_using-snyk/03_wizard.md, _docs_using-snyk/04_test.md, _docs_using-snyk/05_protect.md
Documentation for Yarn support (yay!) in the CLI.
=> feat: add docuomentation for Yarn support

_docs_java/1_support.md, _docs_java/3_gradle.md, _docs_landing/0_intro.md
Adding documentation for the Gradle workaround.
=> Gradle documentation

_docs_github/1_how-to-integrate.md, _docs_github/6_authorizing-github.md
Update documentation to match the new UI and auth flows for GitHub.
=> feat: update documentation for GitHub auth flow

_docs_landing/4_support.md, _layouts/docs.html, _layouts/landing.html
Here you go, Ellen. :) The FAQ's are no more.
=> Fix: FAQ's now links to support

_config.yml, _docs_ci/2_ruby-java-build-integration.md, _docs_landing/0_intro.md, _docs_python/1_support.md, _docs_python/2_testing.md, _docs_python/3_fixing.md, _docs_using-snyk/04_test.md, _layouts/docs.html, _layouts/landing.html, feed.json, python/index.html
=> feat: Python docs

_docs_python/1_support.md
Placeholder PR for Python docs enhancements
=> fix: enhance Python docs

feed.json
I didn't realise that we need to manually add each docs section to the JSON feed too!
=> feat: add cloud foundry and pivotal to docs feed

_docs_github/3_snyk_tests_on_PRs.md, _docs_orgs/2_creating-org.md, _docs_orgs/5_collaborating.md
Updates some of the images in our documentation
=> feat: update images

_docs_using-snyk/04_test.md
Per https://app.intercom.io/a/apps/he1f413x/respond/inbox/conversation/13109978041, `snyk test *` is broken. This should pull it from docs.
=> Removing paragraph on snyk test *

_docs_badges/0_intro.md
Showcases different badge styles available.
=> docs: badge styles

_config.yml, _docs_dotnet/1_support.md, _docs_dotnet/2_testing.md, _docs_using-snyk/00_intro.md, _docs_using-snyk/03_test.md, _docs_using-snyk/08_dev-integration.md, _layouts/docs.html, _layouts/landing.html, dotnet/index.html, feed.json
Docs for NuGet package manager.
I used `.NET` instead of `NuGet` when I saw languages (instead of package managers), such as `Go` specified
=> feat: nuget docs

_docs_using-snyk/03_test.md
=> Lang test notes wording

_docs_github/1_how-to-integrate.md
See https://snyksec.atlassian.net/browse/SC-4535 for details
=> feat: add a note about project auto creation on github

_config.yml, _docs_groups/01_what-is-group.md, _docs_groups/02_creating-groups.md, _docs_groups/03_creating-orgs.md, _docs_groups/04_switching-groups-and-orgs.md, _docs_groups/05_group-overview.md, _layouts/docs.html, feed.json
Adds documentation about our groups
=> feat: add group docs

_docs_licenses/00_about.md, _docs_licenses/01_policy.md, _docs_licenses/02_license-inventory.md, _layouts/docs.html, _layouts/landing.html, feed.json
Adds documentation about our licenses
=> feat: add licenses documentation

_config.yml, _docs_reports/01_overview.md, _docs_reports/02_issues.md, _docs_reports/03_dependencies.md, _docs_reports/04_licenses.md, _layouts/docs.html, _layouts/landing.html, feed.json
=> feat: add reports docs

_config.yml, _docs_github/1_how-to-integrate.md, _docs_github/4_fix_vulnerabilities_web_flow.md, _docs_github/5_disabling_GH_integration.md, _docs_github/6_authorizing-github.md, _docs_gitlab/1_how-to-integrate.md, _docs_gitlab/2_integration_features.md, _docs_gitlab/4_fix_vulnerabilities_web_flow.md, _docs_gitlab/5_disabling_GH_integration.md, _layouts/docs.html, _layouts/landing.html, feed.json
Adds basic gitlab integration docs, and fixes some typos and dodgy styling in the github integration sections.
=> feat: add basic gitlab integration docs

_docs_using-snyk/04_monitor.md
added details for overriding the project name flag
=> feat: added project name override flag

_docs_using-snyk/04_monitor.md
update docs to reflect the error we now throw about invalid names
=> docs: update about invalid names

_config.yml, _docs_service-accounts/0_intro.md, _docs_service-accounts/1_setup.md, _docs_service-accounts/2_deletion.md, _layouts/docs.html, _layouts/landing.html, feed.json
Documentation for the service accounts feature
=> feat: add service account docs [pending feature release]

_docs_broker/5_jira_setup.md, _docs_jira-integration/0_intro.md
Just some minor wording tweaks
=> fix: wording in Jira broker instructions

_docs_aws-lambda/3_adding-lambda-functions.md, _docs_aws-lambda/5_adding-snyk-specific-user.md, _docs_bitbucket-server/00_intro.md, _docs_bitbucket-server/3_adding-bitbucket-server-repos.md, _docs_broker/0_broker.md, _docs_broker/1_snyk-setup.md, _docs_broker/2_github-setup.md, _docs_broker/3_bbserver-setup.md, _docs_broker/4_gitlab-setup.md, _docs_broker/5_jira_setup.md, _docs_broker/6_broker-client-setup.md, _docs_broker/7_snyk-connect.md, _docs_cloud-foundry/3_adding-cloud-foundry-apps.md, _docs_cloud-foundry/5_adding-snyk-specific-user.md, _docs_github/1_how-to-integrate.md, _docs_gitlab/1_how-to-integrate.md, _docs_heroku/3_adding-heroku-projects.md, _docs_heroku/5_adding-snyk-specific-user.md, _docs_jira-integration/0_intro.md, _docs_pivotal-web-services/4_adding-snyk-specific-user.md, _docs_quick-start/2_authentication.md, _docs_quick-start/6_applying-your-choices.md, _docs_reports/03_dependencies.md, _docs_security/3_disclosure-policy.md, _docs_security/4_snyk-vulnerability-disclosure-program.md, _docs_using-snyk/03_test.md, _docs_using-snyk/04_monitor.md
Lots of spelling mistakes. Fixed.
=> fix: all of the spelling

_docs_aws-lambda/1_connecting-to-aws-lambda.md, _docs_aws-lambda/3_adding-lambda-functions.md, _docs_bitbucket-server/1_connecting-to-bitbucket-server.md, _docs_bitbucket-server/3_adding-bitbucket-server-repos.md, _docs_bitbucket/2_configure_bitbucket_pipelines.md, _docs_broker/7_snyk-connect.md, _docs_ci/1_build-integration.md, _docs_ci/2_ruby-java-build-integration.md, _docs_ci/3_API-token-configuration.md, _docs_cloud-foundry/1_connecting-to-cloud-foundry.md, _docs_cloud-foundry/3_adding-cloud-foundry-apps.md, _docs_github/1_how-to-integrate.md, _docs_gitlab/1_how-to-integrate.md, _docs_heroku/1_connecting-to-heroku.md, _docs_heroku/3_adding-heroku-projects.md, _docs_orgs/3_switching-orgs.md, _docs_pivotal-web-services/1_connecting-to-pivotal-web-services.md, _docs_pivotal-web-services/2_adding-pivotal-web-services-apps.md, _docs_quick-start/2_authentication.md, _docs_quick-start/6_applying-your-choices.md, _docs_using-snyk/02_authentication.md, _docs_using-snyk/04_monitor.md, _docs_using-snyk/10_open-source.md, _docs_using-snyk/12_troubleshooting.md, github-integration.md
Updates all snyk.io urls that should now point to app.snyk.io
=> fix: urls pointing to snyk.io that should be pointing to app.snyk.io

_docs_using-snyk/04_monitor.md
Add underscore to valid project names
=> feat: add underscore to valid project names

_docs_broker/5_jira_setup.md, _docs_jira-integration/1_setup.md
It is possible to connect to Jira by username and API token. This is our preferred connection method. Updating docs to reflect this.
=> feat: mention generating API token for Jira integration

_docs_python/1_support.md, _docs_python/2_testing.md, _docs_using-snyk/03_test.md
Adding `pipenv` support on the CLI.
=> docs: pipenv support on the CLI

_docs_docker/1_support.md
changed docker to add on rather than included as part of enterprise
=> fix: docker add on

_docs_groups/03_creating-orgs.md, _docs_groups/04_copying-orgs.md
=> fix: image dimensions

_config.yml, _docs_runtime-protection/00_intro.md, _docs_runtime-protection/1_setup.md, _layouts/docs.html, feed.json, runtime-protection/index.html
Adds Runtime Protection documentation
=> feat: runtime

_docs_runtime-protection/00_intro.md, _docs_runtime-protection/1_nodejs.md, _docs_runtime-protection/2_java.md
Editing for clarity and alignment with blog post
=> fix: reviewed runtime docs

_docs_runtime-protection/00_intro.md
Updates runtime docs with a screenshot. Tweaks wording.
=> chore: add screenshot to runtime docs.

_docs_slack-integration/1_installation.md
Give more advice on generating Slack webhook URLs.
=> feat: improve slack webhooks docs

_docs_nodejs/2_testing.md
=> docs: update nodejs
